### PR TITLE
+ .npmignore, ignoring configuration & tests

### PR DESCRIPTION
**Pull request by cflynn07**

### CODE REVIEW

**Comment by tomekwi** [comment]
Good idea again. I only remember reading that NPM recommends setting the `files` field in the `package.json` – to explicitly *include* important files, instead of excluding.

**Comment by cflynn07** [comment]
@tomekwi I couldn't find that, could you share a link?

**Comment by bkendall** [comment]
Below are the sources I found regarding this question. It doesn't look like either location of the documentation says one or the other is better. It seems like it really comes down to "which list is shorter/easier to maintain". Since this is a _very_ long list of modules that would be included, this `.npmignore` seems reasonable to me.

:+1: 

sources:
- https://docs.npmjs.com/all#keeping-files-out-of-your-package
- https://docs.npmjs.com/files/package.json#files (scroll to the `Files` header)

**Comment by cflynn07** [comment]
Thanks @bkendall, I agree

**Comment by tomekwi** [comment]
> Since this is a very long list of modules that would be included, this .npmignore seems reasonable to me.

Good point – though `files` accepts wildcards, as far as I know. Anyway, this PR is a good thing by all means :)

**Pull request merged**
