### PR TITLE
add converge function

### LINKED ISSUE #53: Idea: `compose` could accept an array of functions
One use case:

```js
[ {a: true, b: false}
, {a: false, b: false}
, {a: true, b: true}
].filter(compose(and
  , [ pluck("a")
    , pluck("b")
    ]
  ));
// » [{a: true, b: true}]
```

### PR DESCRIPTION
**Pull request by stoeffel**
closes #53

### CODE REVIEW

**Comment by tjmehta** [comment]
:+1: LGTM

**Comment by tjmehta** [comment]
Thanks!

**Comment by tjmehta** [comment]
Published: v0.10.0

**Comment by stoeffel** [comment]
yes

**Pull request merged**
