### PR TITLE
proposal to add curry function and tests

### PR DESCRIPTION
**Pull request by stoeffel**
This adds a simple `curry` function that takes either just a function or a function and an integer and returns `n` curried functions.
@tjmehta What do you think about adding this to the lib?

```js
var curry = require('101/curry');

function add(a, b) { return a + b; }

var curriedAdd = curry(add);
var add2 = curriedAdd(2);

add2(6); // 8
add2(8); // 10

function join() { return Array.prototype.slice.call(arguments).join(''); }

curry(join, 3)(1)(0)(1); // "101"
```

### CODE REVIEW

**Comment by tjmehta** [comment]
I am familiar with the concept of currying; although, I do not recall any time I've needed it and could not solve the problem with `bind`. Out of curiousity, would you be able to provide me with a real world example where you needed `curry`?

**Comment by stoeffel** [comment]
You can do most of it without the `curry` function. But `curry` makes it easier to implement a API which allows to use a function curried or not curried.

For example `equals` is currently implemented like this:

```js
module.exports = function (a, b) {
  if (arguments.length === 1) {
    return equals.bind(null, a);
  }
  else {
    return equals(a, b);
  }
};

function equals (a, b) {
  return a === b;
}

equals(1, 1); // => true
equals(1)(1); // => true
```

with `curry` it would be like this:
```js
module.exports = curry(equals);

function equals (a, b) {
  return a === b;
}

equals(1, 1); // => true
equals(1)(1); // => true
```

So curry allows you to simplify your code.

**Comment by tjmehta** [comment]
Cool, thanks for the further explanation. I'll pull it as on of 101's reason for existence is to promote functional programming paradigms in JS.

**Comment by tjmehta** [comment]
published v0.12.0

**Pull request merged**
