### PR TITLE
added indexBy and documentation for it

### LINKED ISSUE #73: proposal: indexBy
Should it work with reduce?
```js
[ 
  { foo: 'bar', bar: 'yo' }, 
  { foo: 'qux' }, 
  { foo: 'flux' }, 
  { foo: 100 }
].reduce(indexBy('foo'), {});
/* returns 
{
  'bar': { foo: 'bar', bar: 'yo' },
  'foo':  { foo: 'qux' }, 
  'flux': { foo: 'flux' },
  '100': { foo: 100 }
}
*/
```
Note: It requires an initial value which makes it a less "plug and play".

Or just 

```js
indexBy(arr, 'foo')
```

### PR DESCRIPTION
**Pull request by tristaaan**
fix #73

### CODE REVIEW

**Comment by stoeffel** [comment]
:+1:

**Comment by bkendall** [comment]
this looks pretty good. @tjmehta will take a look at this in a couple days and give you any additional feedback. but :+1:

**Comment by tjmehta** [comment]
Going to pull this in tonight, sorry for being MIA

**Comment by tjmehta** [comment]
Published v0.18.0 (I pulled in your changes w/ https://github.com/tjmehta/101/pull/101)

**Comment by tjmehta** [comment]
Thank you!

**Pull request closed without merging**
