### PR TITLE
Enable keypaths for set

### LINKED ISSUE #54: `set` doesn't support keypaths
As of 101@0.9.0:

```js
set({a: {b: "c"}}
  , "a.b", "d"
  );
// » {a: {b: "c"}, "a.b": "d"}
```

Maybe that's intended – but [the docs](https://github.com/tjmehta/101#set) say:
>     // supports keypaths by default

### PR DESCRIPTION
**Pull request by tomekwi**
Should close #54

### CODE REVIEW

**Comment by tjmehta** [comment]
:+1:

**Comment by tjmehta** [comment]
how do you think
```js
set(obj, { 'key.path': 1, 'foo.bar': 2 })
```
work?

**Comment by tomekwi** [comment]
> should work?

I've got mixed feelings. Useful thing. But then `set(obj, {foo: 1, bar: 2})` would 100% overlap with assign. Wouldn't it?

Except when set returns a new object instead of extending — as we're considering in #65 :)

**Comment by tjmehta** [comment]
I am thinking about holding on this until keypather get's updated to be more modular (https://github.com/tjmehta/keypather/issues/11). I think I may just then export keypather/set if it supports partial functionality. Are you in dire need of this?

**Comment by tomekwi** [comment]
Hi @tjmehta thanks for looking into this. I needed a quick solution and even keypather wouldn't work for me until tjmehta/keypather#9 is resolved. For now I've falled back to [object-path](http://npm.im/object-path) for now.

But I'm definitely eager to go back to `101/set` once the two things are done.

**Comment by tjmehta** [comment]
merged in with #102

**Comment by tjmehta** [comment]
101@1.0.0

**Pull request closed without merging**
