### PR TITLE
Added is-integer

### PR DESCRIPTION
**Pull request by tristaaan**

### CODE REVIEW

**Comment by tjmehta** [comment]
Thanks @tristaaan !

How does your solution compare to the Polyfill here?
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isInteger

**Comment by tristaaan** [comment]
>.< I rushed a bit on this, didn't even know it was a native function. The polyfill is faster and no doubt covers some unintuitive test cases. Sorry about this, I'll update...

**Comment by tjmehta** [comment]
No worries. I actually had no idea this was included in ES6 either, until I googled.

**Comment by tjmehta** [comment]
:+1: LGTM

**Comment by tjmehta** [comment]
@rsandor your wish is granted.

**Pull request merged**
