### PR TITLE
Add defaults function

### PR DESCRIPTION
**Pull request by jrf0110**
This adds `require('101/defaults')`

### CODE REVIEW

**Comment by tjmehta** [comment]
Took a quick look at this from my phone, is this different from extend/assign?

**Comment by jrf0110** [comment]
Yes, extend/assign will overwrite properties. Defaults checks to make sure the property is undefined first and is only a single source:

```javascript
var myFn = function( options ){
  options = defaults( options, {
    foo: 'bar'
  , bar: 'baz'
  });

  console.log( options );
};

myFn() // { foo: 'bar', bar: 'baz' }
myFn({ foo: 'baz' }) // { foo: 'baz', bar: 'baz' }
```

**Comment by tjmehta** [comment]
Cool this looks good, most all the functions in 101 work as partial functions as well.

Can you add the following functionality?
```js
[{foo:1}, {bar:1}, {qux:1}].map(defaults({ foo:2 })); // [{foo:1}, {bar:1, foo:2}, {qux:1, foo:2}]
```

And then just add it to the Readme (alphabetical order).

Thanks man!

**Comment by jrf0110** [comment]
Sure. I think the partial feature is kinda funky, but I like the terseness compared to using `bind`.

**Comment by tomekwi** [comment]
@tjmehta this seems to be the same as `flip(assign)` from #36. What do you guys think – is a more generic `flip` in the  spirit of 101? If so, I can sketch it out next week.

**Comment by jrf0110** [comment]
@tomekwi `flip(assign)` would produce different behavior than `defaults` since it would mutate the source rather than the target.

So maintaining a single reference to default options would fail:

```javascript
var myFn = (function(){
  var defaultOptions = {
    a: 1
  , b: 2
  };

  return function( options ){
    options = flip( assign )( options, defaultOptions );
    console.log( options );
  };
})();

myFn({ a: 2 });  // { a: 2, b: 2 }
myFn({});  // { a: 2, b: 2 }
```

**Comment by tomekwi** [comment]
True, I didn't think of that.

@tjmehta then let me know if you find the idea of `flip` useful.

**Comment by tjmehta** [comment]
@tomekwi I personally haven't come across the need for `flip` while programming applications since we last talked. If you come across a scenario where you need, it let's reopen the flip issue and report the real world use cases.

**Comment by tjmehta** [comment]
Thanks! I just wrapped this up. 101@v0.9.0

**Comment by jrf0110** [comment]
oh whoops! Totally forgot about this my bad!

**Comment by tjmehta** [comment]
I figured you did, so I just took it up. No problem man, I know how it is.


—
@tjmehta

**Pull request merged**
