### PR TITLE
Return new object in `set`

### PR DESCRIPTION
**Pull request by tomekwi**
As proposed in #64

### CODE REVIEW

**Comment by stoeffel** [comment]
LGTM :deciduous_tree:

**Comment by tjmehta** [comment]
What's the difference with set bs assign if we make this change?

**Comment by stoeffel** [comment]
Only that it returns a ***new*** object instead of changing the passed one.

**Comment by tjmehta** [comment]
Ah whoops. I didn't realize assign and set were so similar, but I just remember assign works to ES6 spec (and doesn't support partial functionality). 

IMO `set` indicates that it is setting the original object, and is more primitive than a clone and set. If a developer wants to clone the object before setting properties on them they could use `101/clone` and then `101/set`. However, if we make this PR's change and a developer is actually wanting to set properties on the original objects it would not be possible with a method provided in 101.

**Comment by stoeffel** [comment]
> IMO set indicates that it is setting the original object

true

If we don't change the behaviour of `set` we should at least change the docs "returns a new obj"

**Comment by tjmehta** [comment]
@stoeffel I think you may have a typo above, so it's not clear what you mean. Currently set modifies the original object. Are you just suggesting to state that it "modifies the original" in the docs.

**Comment by tjmehta** [comment]
Since, @tomekwi was confused on set's functionality, I agree we should definitely make it more clear in the docs.

Do you guys agree about keeping set's functionality as is, because it is more primitive and can be composed with clone to produce the PR's behavior?

**Comment by stoeffel** [comment]
> Do you guys agree about keeping set's functionality as is, because it is more primitive and can be composed with clone to produce the PR's behavior?

agreed :+1:

**Comment by tomekwi** [comment]
> can be composed with clone

Good idea. But wait. `compose(clone, set)` would clone after setting. Would `compose(set, clone)(obj, key, value)` work like  `set(clone(obj), key, value)` then?

**Comment by stoeffel** [comment]
> compose(set, clone)(obj, key, value) work like set(clone(obj), key, value) then?

Nope, this wouldn't be the same. But users can use it like this `set(clone(obj), key, value)` it's easy enough (IMO).

This `compose(set, clone)(obj, key, value)` is equivalent to `set(clone(obj, key, value))`

If we add a flip method we could do
```js
compose(curry(flip(set), value, key), clone)
```

or if we make `curry` smarter we could add some thing like https://github.com/stoeffel/chickencurry#placeholder
```js
compose(curry(set, void 0, value, key), clone)
```

**Comment by tomekwi** [comment]
> This compose(set, clone)(obj, key, value) is equivalent to set(clone(obj, key, value))

So I thought, I just wasn't sure.

IMO it's not as straightforward as we'd like it — the `compose` way. I'd still really love `set` to return a new object. Here's why:
- It's consistent with `omit`.
- Immutability is at the heart of functional programming. Facebook had a take at that and ended up with a super-heavyweight immutable.js (over 50KB minified). I haven't checked `set` but I guess it won't be more than 10 KB with keypather and clone. And that'd probably become no more than 5 KB with ES6's assign. Anyway `set` could be the ultimate lightweight alternative to immutable.js.
- We have lots of ways to do `set` without cloning. `assign`, the native keypather, or just `obj[key] = value`.
- Array functions like map, filter, or reduce are immutable.
- So mutability + array functions can be deadly. Even what happens in the example from the docs is really counterintuitive:

```js
var obj = {
  foo: 1,
  bar: 2
};

// use it with array.map
var array = [obj, obj, obj]

array.map(set('foo', 100));
// `obj.foo = 100` has exactly the same effect
```

...isn't that confusing?

To be honest, this immutability has drawn me to 101. Like a gasp of fresh air in the ever-changing "everything is an object" environment. Let's not lose this!

**Comment by stoeffel** [comment]
> Immutability is at the heart of functional programming.

Valid point since the readme states:

> 101 will only duplicate vanilla JS to provide Functional Programming paradigms

If we change `set` to return a new object we should check if all other functions are immutable.

I'm still torn between changing and not changing. But either way it should be documented correctly.

**Comment by tomekwi** [comment]
> If we change `set` to return a new object we should check if all other functions are immutable.

It shouldn't be much of a change, if any. As far as I've seen, the only other function so far which deals with objects and changes their value is `omit`. It [already returns a new object](https://github.com/tjmehta/101/blob/master/omit.js#L34), just as [stated in the docs and readme](https://github.com/tjmehta/101/blob/master/omit.js#L9).

**Comment by tjmehta** [comment]
Hey guys thanks for you input, your contributions really means a lot. I've loved our conversations thus far. 

I wanted to reply to explain my original thoughts with you guy on why I originally created set.
So my original intention for creating set was to create a functional version of `obj[key] = val`.
This way I could use it as a partial function with `Array` functions. I mistakenly allowed non-partial
usage `set(obj, 'key', val)`, but I really should have not allowed this behavior (one should just
use obj['key']=val).

If we change set's behavior to return new objects this could break functionality of being able
to set properties on prototypical-class instances `[new Cat(1), new Cat(2)].map(set('fur', 'spotted'))`.
I do not agree that `set` should parallel the behavior of `omit` (`omit` behaves like `pick` and `pluck`).
`set` should parallel `del` (which does not exist in 101 yet).

If I were to create `del` in 101, it would be a functional version of  `delete obj['key']`, and only allow partial
functionality. Now that you have been introduced to `del`, how do you guys think should it work? Does it
promote leaving `set`'s behavior as is or does it help us see why `set` should be changed?

The big point for me to keep `set`'s behavior is that changing it makes it lose functionality. 
101 would not longer provide any method for setting properties on items in an array; while,
if we leave it it can be very easily composed with clone. Since it can be composed to produce
the PR's behavior, that would indicate set is more primitive as is (which is more flexible).

**Comment by tomekwi** [comment]
Then how about
* keeping `set` as it is and pairing it consistently with `del` (good idea @tjmehta!)
* and making a new function `insert` which creates a new object – in pair with `omit`?

> If we change set's behavior to return new objects this could break functionality of being able to set properties on prototypical-class instances
It looks like `clone` is smart enough to leave the prototype chain intact. Check it out: http://requirebin.com/?gist=a8b46472118baa20ec6f

> it can be very easily composed with clone
Can you post an example @tjmehta? I tried to figure it out above, but couldn't find an easy way.

**Comment by tomekwi** [comment]
I'm not saying we should change `set` if you don't like it @tjmehta – just that we need `insert` on top of that :)

**Comment by tomekwi** [comment]
Other ideas for `insert`'s name:
* `put` (my favourite)
* `inject`
* `modify`
* ...?

**Comment by stoeffel** [comment]
> keeping set as it is and pairing it consistently with del (good idea @tjmehta!)

:+1:

You could compose `insert` like this:

```js
var curry = require('101/curry')
var compose = require('101/compose')
var set = require('101/set')
var clone = require('101/clone')

var insert = compose(curry(set, 3), clone);

var obj = { foo: 1 }
insert(obj)('bar', 2)
```

http://requirebin.com/?gist=bb18a4f8a190bbf018dc

**Comment by stoeffel** [comment]
> put (my favourite)

:+1:

**Comment by tjmehta** [comment]
I like the idea of 'put'!

**Comment by stoeffel** [comment]
We should not forget to update the doc:

`returns a new obj with the key and value set`
to
`returns the same obj with the key and value set`

**Comment by tomekwi** [comment]
:+1: :+1: :+1:

I'd be thrilled to do this :) But have no time until next week. Are you guys OK to wait?

**Comment by stoeffel** [comment]
> I'd be thrilled to do this :) But have no time until next week. Are you guys OK to wait?

sure :+1:

**Comment by tjmehta** [comment]
@tomekwi :+1:

**Pull request closed without merging**
